#!/usr/bin/env python
# coding: utf-8

# In[15]:


# answers, don't look please
ans_map = '3679'
ans_galaxy = 'ngc6946'
ans_dec = '10'
ans_ra = '36'
ans_max = '0.00365'
ans_password = 'Sunny=Best'


# In[4]:


print("Welcome to my astro game. This game is inspired by the midterm (because my coding skills don't go much further than that) and the game Outer Wilds. Now to set the scene here: You are on a spaceship, traveling through the solar system. However, the pilot got unwell right before take-off, so you had to sub for him. You are new to the ship, however the ship has been set to autopilot for the time being. However you do need to set the destination. Good luck!")


# In[5]:


print("First of all, you need to find the cockpit. The ship is very big, but luckily the previous pilot left some of his notes around the ship. Near the entrance you find a framed map however.")


# In[6]:


import numpy as np
import matplotlib.pyplot as plt

image = np.zeros(126).reshape(14, 9)
image[1, 4] = 2
image[2:4, 3:-3] = 2
image[4: -5, 2:-2] = 2
image[-4, 4] = 1
image[-5, 3:-3] = 2
image[-3, 3] = 1
image[-2, 6] = 1
image[-1, 4] = 1
image[3, 5] = 1.5
fig, frame = plt.subplots()
frame.imshow(image, 'hot')
frame.set_xticks([])
frame.set_yticks([])
plt.show()


# In[ ]:


print("Aha, so maybe the yellow dot is the cockpit? It won't do harm to take a look. Luckily the ship has signs to the right rooms. To do that however you need to find the right room number. The room number is found with the following database.")


# In[13]:


import numpy as np
txt = np.loadtxt('rooms')
print(txt)


# In[ ]:


# write your code here


# In[9]:


import random as random

random_loc = ['the kitchen. You grab some food just in case.', 'the toilet. It smells.', 'the bathroom. The shower looks incredibly clean.', 'a bedroom. Not even yours!']
rand_int = random.randint(0, len(random_loc) -1)

index = input()
print(f'You travel to the index {index} and you find...')
if index == ans_map:
    print('the cockpit! You did it!')
else:
    print(f'{random_loc[rand_int]} This is not the cockpit though. Your index must be wrong then.')



# In[ ]:


print("You found the cockpit. Now you just need to check the destination. But first you must log into the previous pilot's account. But you don't know the password or username! You look around you and find a little notebook. When you flip through it you see a bunch of letters. Useless! But just as you're about to give up a piece of paper falls out. It has the following text on it:")


# In[ ]:


print("I accidentally got an autogenerated username. Oops! I am very lucky it's easy to remember though. Who could forget the peak brightness of my favourite galaxy? And that at the declination of my lucky number and the right ascension of my daughter's lucky number!")


# In[ ]:


print("Okay. The guy is a weirdo. You do remember him saying something about lucky numbers. It was the 5th number that wasn't divisable by 8 or 3. Why? No clue.")


# In[ ]:


print("His daughter's favourite number however, he has also told you many times. It's the 3rd number that is divisable by 4 and 3. I guess she takes after him.")


# In[ ]:


print("But what is his favourite galaxy? Well, there are a few options:")


# In[ ]:


Fav_galaxies = {'Milky Way', 'm101', 'Andromeda Galaxy', 'ngc6946'}


# In[10]:


print("In order to remind himself he has written down an equation to remember the index.")

print(f"favourite galaxy = (1 + 2i)^2 \ i + 1 - (2 + 3i)")


# In[ ]:


print("That should give it away, shouldn't it? You can decide to do it all in one go or you can do it step by step. If you want to do it step by step you can follow the next steps: Let's start with the right galaxy")


# In[ ]:


galaxy = input('The right galaxy is: ')
if galaxy == ans_galaxy:
    print("Yes! That's correct")
else:
    print("Hmm. That galaxy doesn't seem to be in the database of your computer. Maybe you need a different one?")


# In[ ]:


print("Great! now we can continue with the indices.")


# In[ ]:


dec = input("The declination is: ")
r_a = input("The right ascension is: ")

if dec == ans_dec and r_a == ans_ra:
    print("Those numbers are correct, good job!")
else:
    print("Those numbers don't look right...")


# Now you have the indices and the galaxy. You put those values in the database and get the following plot. Now you just have to find the peak brightness. You can round to five decimals.

# In[2]:


import astropy.io.fits as fits
hdulist = fits.open(f'{ans_galaxy}.fits')
hdr = hdulist[0].header
dat = hdulist[0].data

fig2, ax = plt.subplots(1, 1)
data = np.asarray(dat)[:, int(ans_ra), int(ans_dec)]
ax.set_xlabel(hdr['CTYPE3'])
ax.set_ylabel(hdr['BUNIT'])

plt.plot(data)
plt.show()


# In[ ]:


username = input('username: ')
if username == ans_max:
    print("The username is correct! Now only the password is left.")
else:
    print("The username is incorrect. You must have made a mistake somewhere.")


# In[ ]:


print("On the note he has also written a password reminder: My password is the phrase in this notebook corresponding to the indices of the first 11 prime numbers in the fibonacci sequence.")


# In[34]:


text = list(open('password.txt').read())

# write your code here


# In[ ]:


password = input('Password: ')

if password == ans_password:
    print("You're logged in!")
else:
    print("Incorrect password. Try again.")


# In[ ]:


print("Okay. Now we just need to set the destination. The code for the new destination is 8492795. Now you just have to fill that into the computer.")


# In[3]:


import matplotlib.image as im
final_destination = input('Input final destination:')
if final_destination == '8492795':   
    print('New destination set:')
    img = im.imread(f'{final_destination}.png')
    fig, ax = plt.subplots()
    ax.imshow(img)
    ax.axis('off')
    plt.show()
else:
    print('Final location not recognised')


# In[ ]:


print("You did it! You succesfully set the location of your spaceship and are now safely flying towards 100% for the last session quiz")


# In[ ]: